version: '{branch}-{build}'
image: Visual Studio 2015
configuration: Release
clone_depth: 5
clone_folder: c:\stellarium
environment:
  matrix:
  - platform: x64
    qt: msvc2015_64
    msvcname: Visual Studio 14 2015 Win64
  - platform: x86
    qt: msvc2015
    msvcname: Visual Studio 14 2015
before_build:
- cmd: >-
    set PATH=C:\Qt\5.9.3\%qt%\bin;%PATH%

    cd c:\stellarium

    mkdir build-%qt% && cd build-%qt%

    cmake -DENABLE_TESTING=1 -G "%msvcname%" ..
build:
  project: c:\stellarium\build-%qt%\Stellarium.sln
  parallel: true
  verbosity: minimal
test_script:
- cmd: ctest --output-on-failure
notifications:
- provider: Email
  to:
  - alex.v.wolf@gmail.com
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true
