version: '{branch}-{build}'
# build Configuration
configuration: Release
# clone directory
clone_folder: c:\stellarium
# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true
# environment variables
environment:
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    platform: x64
    qtver: 5.9
    qtbin: msvc2015_64
    msvcname: Visual Studio 14 2015 Win64 
    packaging: true
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    platform: Win32
    qtver: 5.9
    qtbin: msvc2015
    msvcname: Visual Studio 14 2015
    packaging: true
#  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
#    platform: x64
#    qtver: 5.12
#    qtbin: msvc2017_64
#    msvcname: Visual Studio 15 2017 Win64
#    packaging: false
#  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
#    platform: Win32
#    qtver: 5.12
#    qtbin: msvc2017
#    msvcname: Visual Studio 15 2017
#    packaging: false
  
before_build:
  - set INNSPATH=C:\Program Files (x86)\Inno Setup 5
  - set PATH=C:\Qt\%qtver%\%qtbin%\bin;%INNSPATH%;%PATH%
  - appveyor DownloadFile https://github.com/Stellarium/stellarium-data/releases/download/guide/guide.pdf -FileName c:\stellarium\guide\guide.pdf
  - mkdir stellarium-%qtver%-%qtbin%
  - cd c:\stellarium
  - mkdir build-%qtver%-%qtbin% && cd build-%qtver%-%qtbin%
  - cmake -DENABLE_TESTING=1 -DCMAKE_INSTALL_PREFIX=c:\stellarium-%qtver%-%qtbin% -G "%msvcname%" ..

build:
  project: c:\stellarium\build-%qtver%-%qtbin%\Stellarium.sln
  parallel: true
  verbosity: minimal
  
test_script:
  - ctest --output-on-failure
  
after_test:
  - cmake --build c:\stellarium\build-%qtver%-%qtbin%\ --config %configuration% --target install
  - if [%packaging%]==[true] (
      appveyor DownloadFile https://github.com/Stellarium/stellarium-data/releases/download/qt-5.6/libGLES-%platform%.zip -FileName c:\stellarium\build-%qtver%-%qtbin%\libGLES.zip &&
      7z e c:\stellarium\build-%qtver%-%qtbin%\libGLES.zip -aoa -oc:\stellarium-%qtver%-%qtbin%\qt5stuff
    )
  - cmake --build c:\stellarium\build-%qtver%-%qtbin%\ --config %configuration% --target stellarium-installer
#  - if [%packaging%]==[true] ( for /R c:\stellarium\installers %a in (stellarium*.exe) do appveyor PushArtifact %a )

artifacts:
- path: 'installers\stellarium*.exe'
  name: stellarium-installer

# deployment
deploy:
- provider: Webhook
  url: https://app.signpath.io/API/v1/a6a9173a-feb5-41ae-8973-8ca75af5e233/Integrations/AppVeyor?ProjectKey=stellarium&SigningPolicyKey=release-signing
  authorization:
    secure: k9Hka8MA6UONiSbKZeAv5koMEljPXgEZ7o1FbvEHRlPFFHMGzQcS6MQsvy53VxeTpG4Kw98FU0VXusbXoKLzug==
  on:
    branch: release
    packaging: true

notifications:
- provider: Email
  to:
  - alex.v.wolf@gmail.com
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true
