#ifndef LIBSTELLARIUMGLOBAL_H
#define LIBSTELLARIUMGLOBAL_H

#include <QtCore/qglobal.h>

#if defined(STELLARIUM_LIBRARY)
#  define STELLARIUMSHARED_EXPORT Q_DECL_EXPORT
#else
#  define STELLARIUMSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBSTELLARIUMGLOBAL_H
